-- ==============================================================================
-- Migration: 20261005000008_storage_documents_bucket.sql
-- Note: This draft migration has been superseded by
--       20261005000009_storage_documents_hardening.sql
-- ==============================================================================
